### ISSUE TITLE
can not create a project

### ISSUE THREAD

**Issue by zoneby-Alex** [bkntr/napari-brainways#22]
in ubuntu 22.04 
when i try open/new a project ,the folder item cannot open/save even if i create a new folder
Does this require a specific file format?

**Comment by bkntr** [comment]
Are you getting an error? Can you share an error log or a screenshot?

**Comment by zoneby-Alex** [comment]
![截图 2024-08-02 10-54-51](https://github.com/user-attachments/assets/c620b4a4-d649-467a-94bb-85d726159be7)
![截图 2024-08-02 10-55-25](https://github.com/user-attachments/assets/00cedd6c-7113-4f42-b40d-7f8f3fd58516)
When I click 'new' the window's 'save' is not available even though I created an empty folder
The 'open' of the same window is also unavailable when you click 'open'

**Comment by bkntr** [comment]
when you create a new project, got into an empty directory and type a name for the file, then you can save the new project
